export const photoss = [
    {
        id:1,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-1.jpg'
    },
    {
        id:2,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-2.jpg'
    },
    {
        id:3,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-3.jpg'
    },
    {
        id:4,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-4.jpg'
    },
    {
        id:5,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-5.jpg'
    },
    {
        id:6,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-6.jpg'
    },
    {
        id:7,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-7.jpg'
    },
    {
        id:8,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-8.jpg'
    },
    {
        id:9,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-9.jpg'
    },
    {
        id:10,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-10.jpg'
    },
    {
        id:11,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-9.jpg'
    },
    {
        id:12,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-10.jpg'
    },
    {
        id:13,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-9.jpg'
    },
    {
        id:14,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-10.jpg'
    },
    {
        id:15,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-9.jpg'
    },
    {
        id:16,
        image:'https://bootstrapmade.com/demo/templates/PhotoFolio/assets/img/gallery/gallery-10.jpg'
    }
]